# GitHub action to build LAMMPS on Linux and run selected regression tests
name: "Quick Regression Test"

on:
  push:
    branches:
      - develop
      - quick-regression
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    name: Quick Regression Test
    if: ${{ github.repository == 'lammps/lammps' }}
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: false

    - name: Install extra packages
      run: |
        sudo apt-get install -y ccache ninja-build
        sudo apt-get install -y libeigen3-dev libgsl-dev libcurl4-openssl-dev python3-dev

    - name: Create Build Environment
      run: mkdir build

    - name: Set up ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: linux-quick-ccache-${{ github.sha }}
        restore-keys: linux-quick-ccache-

    - name: Building LAMMPS via CMake
      shell: bash
      run: |
        ccache -z
        python3 -m venv linuxenv
        source linuxenv/bin/activate
        python3 -m pip install numpy
        python3 -m pip install pyyaml
        python3 -m pip install junit_xml
        cmake -S cmake -B build \
              -C cmake/presets/gcc.cmake \
              -C cmake/presets/most.cmake \
              -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache \
              -D BUILD_SHARED_LIBS=off \
              -D DOWNLOAD_POTENTIALS=off \
              -D PKG_MANIFOLD=on \
              -D PKG_ML-PACE=on \
              -D PKG_ML-RANN=on \
              -D PKG_RHEO=on \
              -D PKG_PTM=on \
              -D PKG_PYTHON=on \
              -D PKG_QTB=on \
              -D PKG_SMTBQ=on \
              -G Ninja
        cmake --build build
        ccache -s

    - name: Run Selected Regression Tests
      shell: bash
      run: |
        source linuxenv/bin/activate
        python3 tools/regression-tests/get-quick-list.py
        python3 tools/regression-tests/run_tests.py \
               --lmp-bin=build/lmp \
               --config-file=tools/regression-tests/config_serial.yaml \
               --list-input=folder_list.txt
        tar -cvf quick-regression-test.tar run.log progress.yaml

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quick-regression-test-artifact
        path: quick-regression-test.tar


