# GitHub action to build LAMMPS on Linux and run standard unit tests
name: "Linux Unit Test"

on:
  push:
    branches:
      - develop
      - quick-regression
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    name: Quick Regression Test
    if: ${{ github.repository == 'lammps/lammps' }}
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install extra packages
      run: |
        sudo apt-get install -y ccache mold ninja-build
        sudo apt-get install -y libeigen3-dev libgsl-dev libcurl4-openssl-dev python3-dev

    - name: Create Build Environment
      run: mkdir build

    - name: Set up ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: linux-unit-ccache-${{ github.sha }}
        restore-keys: linux-unit-ccache-

    - name: Building LAMMPS via CMake
      shell: bash
      run: |
        ccache -z
        python3 -m venv linuxenv
        source linuxenv/bin/activate
        python3 -m pip install numpy
        python3 -m pip install pyyaml
        cmake -S cmake -B build \
              -C cmake/presets/gcc.cmake \
              -C cmake/presets/most.cmake \
              -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache \
              -D BUILD_SHARED_LIBS=on \
              -D LAMMPS_SIZES=bigbig \
              -D DOWNLOAD_POTENTIALS=off \
              -D ENABLE_TESTING=on \
              -D PKG_MANIFOLD=on \
              -D PKG_ML-PACE=on \
              -D PKG_ML-RANN=on \
              -D PKG_RHEO=on \
              -D PKG_PTM=on \
              -D PKG_PYTHON=on \
              -D PKG_QTB=on \
              -D PKG_SMTBQ=on \
              -G Ninja
        cmake --build build
        ccache -s

    - name: Run Tests
      working-directory: build
      shell: bash
      run: ctest -V
